### ISSUE TITLE
Appears not to work

### ISSUE THREAD

**Issue by ramonfincken** [pcfreak30/dedicated-transients#1]
WP 6.4.3

creates table, but transients keep beeing added to the options table

**Comment by pcfreak30** [comment]
Hello, unfortunately my current work has put my energy outside the WP ecosystem.

I am open to any PR's to fix issues, but I am not actively developing inside WP right now. I hope that changes in the future, but it is not the case now.

Sorry.

Kudos.

**Comment by ramonfincken** [comment]
Understandable. 

Thanks for letting me know.
